name: random_folder
description: A Dart random folder generator that uses random words and numbers to create directory for new projects
version: 1.0.1
homepage: https://github.com/dnbailey/random_folder
author: Nathan Bailey <dev@dnbailey.org>
repository: https://github.com/dnbailey/random_folder

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  english_words: ^3.1.5
  args: ^1.5.2

executables:
  mkrdir: main

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
