name: random_folder
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
author: Nathan Bailey <dev@dnbailey.org>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  english_words: ^3.1.5

executables:
  mkrdir: main

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
